### ISSUE TITLE
Handling Device Switching Keys

### ISSUE THREAD

**Issue by msob** [Logitech/cpg-docs#19]
I don't know a better place to ask for this, hoping for an quite official answer.

Is there any possibility to detect an input device has been switched to another device inside my custom software?
Maybe is there even a possibillity to trigger a device switch from software?

**Comment by pfps** [comment]
If you are asking whether a Logitech HID++ device sends a message when it switches to another host, then no.  The device just disappears.   If there is an open read on the device then the read will fail, so that can be used.  If the device is connected to a Unifying Receiver the receiver will send a disconnect message.

It is possible to send a message that switches the device between hosts.  Solaar (https://github.com/pwr-Solaar/Solaar) does this.  Solaar also has a tool - hidconsole - that shows the HID++ messages a device sends and can be used to send HID++ messages to a device.

This is all only for devices that switch between hosts, generally meaning that they have keys or buttons that perform this action.

**Comment by msob** [comment]
Wow, some months ago I searched so hard for a solution, but did not find a working one.

I will give Solaar a try, thank you very much!

**Comment by xnlcasad** [comment]
Thanks Peter !
