### ISSUE TITLE
description for REPORT RATE 

### ISSUE THREAD

**Issue by pfps** [Logitech/cpg-docs#9]
Solaar has a  bug that could be fixed if we had documentation for REPORT RATE  {8060}.  

https://github.com/pwr-Solaar/Solaar/issues/792

**Comment by FFY00** [comment]
We should add documentation here but note that this is already implemented in libratbag and that should give you all the information required for the Solaar implmentation.

https://github.com/libratbag/libratbag/blob/f61485c6032b56e6d07d11f0fea206679bc3a48d/src/hidpp20.c#L1687

**Comment by pfps** [comment]
It should, but I can't seem to correctly determine how to set the report rate from the libratbag code.

**Comment by FFY00** [comment]
Feature `0x8060`, function `2` (`SET_REPORT_RATE`), the first byte of the arguments (`args[0]`) is the report rate in milliseconds. You may wish to do some conversion like [this](https://github.com/libratbag/libratbag/commit/5f5e2945985229bdf1679f69629536c71422cffa#diff-be79c5bd42c79cdb558a9e9f36e29f7bR849), but for Solaar I think it's best if we export the milliseconds instead of the frequency.

**Comment by FFY00** [comment]
Also, keep in mind if the device supports onboard profiles (`0x8100`) it would be much better to set the report rate that way.
